#!/usr/bin/env python3

from follower import controllers

import rospy


if __name__ == '__main__':
    
    try:

        rospy.init_node('follower', anonymous=True)

        controllers.PID_Stanley()

        rospy.spin()

    except rospy.ROSInterruptException:
        pass
